server:
  port: 8081

app:
  secretKey: ${SECRETKEY}
  jwtValidity: ${VALIDATITY}

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: gokullogan10@gmail.com
    password: ${APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    mongodb:
      database: ${MONGO_DATABASE}
      uri: mongodb+srv://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_CLUSTER}
  application:
    name: SECURITY-SERVICE


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    hostname: localhost

